### ISSUE TITLE
window.history会一直增加问题

### ISSUE THREAD

**Issue by ychxx** [ZTStory/vue-composition-demo#1]
感谢作者，这个方法很巧妙！
但是window.history会一直增加，有没有方法清除

**Comment by ZTStory** [comment]
我做了简单的测试与复现，你是说demo中随页面深度变化，导致history增加吗？

这边的测试结果是：history.length 在对应的模块深度中有所保留，最深为 KeepAlive 的 4，当你回退到首页，history 还会保留之前模块的forward路径，如果此时你另外点开了切换动画，则 history.length 会重新归为 2

实际上灵活清理缓存：
1、通过改变 KeepAlive.caches 
2、或者配置 excludes 使缓存失效

来达到目的，并不会对 vue-router 以及 history 做一些人为干涉

**Comment by ychxx** [comment]
跟demo的代码对比下，发现我代码里有一个功能用到了路由的replace，就会出现history增加问题
将select.vue文件里的router.back();替换成router.replace('keepAliveInput');也会出现这种情况。
请问有办法解决么。

**Comment by ZTStory** [comment]
按照你说的，我替换为router.replace('keepAliveInput')了，但是history.length并没有变为4而是3，说明replace没有增加history的长度，你想说返回到首页的时候 history.length 依然是 3 吗？还是说你业务逻辑里有要处理 history 的情况？

history 本身并不表示当前页面栈的数量
